---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[openstack-paas::server]
      - recipe[openstack-paas::identity_register]
      - recipe[openstack-paas::client]
      - recipe[openstack-common::openrc]
    attributes:
      openstack:
        paas:
            services: ['solum-api']
      apache2:
        default_site_enabled: false
